version: '3'
services:
  web:
    build: .
    command: sh -c 'npm run start:dev'
    volumes:
      - .:/api-patients
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local
