version: '3'
services:

  api_manage-patients:
    build: .
    command: sh -c 'npm install; npm run start:dev'
    volumes:
      - ./api-manage-patients:/app
    ports:
      - "3004:3004"
    depends_on:
      - mongo_db

  api_manage-files:
    build: .
    command: sh -c 'npm install; npm run start:dev'
    volumes:
      - ./api-manage-files:/app
    ports:
      - "3003:3003"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
    driver: local
